import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Box, MainSection } from "@/components/common/Box";
import NavBar from "@/components/NavBar";
import Profile from "@/components/Profile";
import AboutMe from "@/components/AboutMe";

export default function Home() {
  return (
    <>
      <Head>
        <title>My website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <Box>
          <MainSection>
            <Profile />
            <AboutMe />
          </MainSection>
        </Box>
      </main>
    </>
  );
}
