import Head from "next/head";
import { useState } from "react";
import { Box, MainSection } from "@/components/common/Box";
import NavBar from "@/components/NavBar";
import Profile from "@/components/Profile";
import AboutMe from "@/components/AboutMe";
import Footer from "@/components/Footer";
import { Main } from "@/components/common/Main";
import { navbarList } from "data/navbarList";

export default function Home() {
  const [content, setContent] = useState(navbarList[0]);
  const handleClick = (contentName: string) => {
    setContent(contentName);
  };
  return (
    <>
      <Head>
        <title>My website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar handleClick={handleClick} content={content} />
      <Main>
        <Box>
          <MainSection>
            <Profile />
            {content === navbarList[0] ? <AboutMe /> : null}
          </MainSection>
        </Box>
      </Main>
      <Footer />
    </>
  );
}
