import Head from "next/head";
import { useState } from "react";
import { MainSection, PageContainer } from "@/components/common/Box";
import NavBar from "@/components/NavBar";
import Profile from "@/components/Profile";
import Contents from "@/components/Contents";
import { Main } from "@/components/common/Main";
import { navbarList } from "data/navbarList";

export default function Home() {
  const [content, setContent] = useState(navbarList[0]);
  const handleClick = (contentName: string) => {
    setContent(contentName);
  };
  return (
    <PageContainer>
      <Head>
        <title>My website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar handleClick={handleClick} content={content} />
      <Main>
        <MainSection fullW>
          <Profile />
          <Contents content={content} navbarList={navbarList} />
        </MainSection>
      </Main>
    </PageContainer>
  );
}
